package View;

import Controller.BoardController;
import Observer.Observer;

import javax.swing.*;
import java.awt.*;

public class BoardView extends JFrame implements Observer {

    private BoardController boardController;

    public BoardView(BoardController boardController) {
        this.boardController = boardController;
        int gridCells = boardController.getGridCells();
        JButton[][] gridButtons = new JButton[gridCells][gridCells];

        // Configurar el JFrame

        setTitle("Hysteria Game");
        setLayout(new GridLayout(gridCells, gridCells));
        setSize(500, 400);
        setLocationRelativeTo(null);

        // Initialize the grid of buttons
        for (int i = 0; i < gridCells; i++) {
            for (int j = 0; j < gridCells; j++) {
                gridButtons[i][j] = new JButton();
                gridButtons[i][j].setBackground(Color.WHITE);
                int x = i, y = j;
                gridButtons[i][j].addActionListener(e -> boardController.updateBoardOnClick(x, y));
                add(gridButtons[i][j]);
            }
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setBackground(new Color(-16770512));
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer2, gbc);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */

}
