package View;

import Controller.LevelController;
import Model.LevelModel;

import javax.swing.*;
import java.awt.*;
import Observer.Observer;

public class LevelView extends JFrame implements Observer {
    private JButton button1;
    private JPanel panel1;
    private JButton jugarButton;
    private JComboBox comboBox1;
    private LevelController levelController;


    public LevelView(LevelController levelController) {
        this.levelController = levelController;

        // Configurar el JFrame
        setTitle("Hysteria Level Selector");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(500, 400);
        setLocationRelativeTo(null);

        // Inicializar los componentes GUI
        $$$setupUI$$$();

        // Agregar el panel1 al JFrame
        getContentPane().add(panel1);

        // Si usas CardLayout, muestra la tarjeta correcta (panel2)
        CardLayout cardLayout = (CardLayout) panel1.getLayout();
        cardLayout.show(panel1, "Card2");  // Mostrar el panel con el formulario

        // Hacer visible el JFrame
        setVisible(true);
    }
    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new CardLayout(0, 0));
        button1 = new JButton();
        button1.setText("Button");
        panel1.add(button1, "Card1");
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel1.add(panel2, "Card2");
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Seleccione un nivel:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label1, gbc);
        jugarButton = new JButton();
        jugarButton.setText("Jugar");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(jugarButton, gbc);
        comboBox1 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Facil");
        defaultComboBoxModel1.addElement("Medio");
        defaultComboBoxModel1.addElement("Dificil");
        comboBox1.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        panel2.add(comboBox1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Bienvenido a Histeria!");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
