package View;

import Controller.LevelController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import Observers.Observer;

public class LevelView extends JFrame implements Observer {
    private JPanel panel1;
    private JButton playButton;
    private JComboBox difficultySelector;
    private LevelController levelController;

    public LevelView(LevelController levelController) {
        this.levelController = levelController;

        // Configurar el JFrame
        setTitle("Hysteria");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(500, 400);
        setLocationRelativeTo(null);

        // Inicializar los componentes GUI
        $$$setupUI$$$();

        // Agregar el panel1 al JFrame
        getContentPane().add(panel1);

        // Si usas CardLayout, muestra la tarjeta correcta (panel2)
        CardLayout cardLayout = (CardLayout) panel1.getLayout();
        cardLayout.show(panel1, "Card2");  // Mostrar el panel con el formulario

        // Hacer visible el JFrame
        setVisible(true);
    }
    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new CardLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel1.add(panel2, "Card2");
        final JPanel spacer1 = new JPanel();

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer1, gbc);

        final JLabel label2 = new JLabel();
        label2.setText("Bienvenido a Histeria!");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label2, gbc);

        final JLabel label1 = new JLabel();
        label1.setText("Seleccione un nivel:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label1, gbc);

        difficultySelector = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("FACIL");
        defaultComboBoxModel1.addElement("MEDIO");
        defaultComboBoxModel1.addElement("DIFICIL");
        difficultySelector.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        panel2.add(difficultySelector, gbc);

        playButton = new JButton();
        playButton.setText("Jugar");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        playButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                levelController.establecerDificultad(difficultySelector.getSelectedItem().toString());
                dispose();
            }
        });

        panel2.add(playButton, gbc);

    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    @Override
    public void notificar() {
    }
}
